version: "3"
services:
  frontend:
    build: .
    image: hotel_app_frontend_single_node_memdb
    entrypoint: frontend
    container_name: 'hotel_app_frontend'
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: none          
      placement:
        constraints: ["node.hostname == ${NODE0}"]   

  profile:
    build: .
    image: hotel_app_profile_single_node_memdb
    entrypoint: profile
    container_name: 'hotel_app_profile'
    ports:
      - "8081:8081"
    deploy:
      restart_policy:
        condition: none        
      placement:
        constraints: ["node.hostname == ${NODE1}"]  

  search:
    build: .
    image: hotel_app_search_single_node_memdb
    entrypoint: search
    container_name: 'hotel_app_search'
    ports:
      - "8082:8082"
    deploy:
      restart_policy:
        condition: none          
      placement:
        constraints: ["node.hostname == ${NODE2}"]  

  geo:
    build: .
    image: hotel_app_geo_single_node_memdb
    container_name: 'hotel_app_geo'
    entrypoint: geo
    ports:
      - "8083:8083"
    deploy:
      restart_policy:
        condition: none          
      placement:
        constraints: ["node.hostname == ${NODE3}"]  

  rate:
    build: .
    image: hotel_app_rate_single_node_memdb
    container_name: 'hotel_app_rate'
    entrypoint: rate
    ports:
      - "8084:8084"
    deploy:
      restart_policy:
        condition: none          
      placement:
        constraints: ["node.hostname == ${NODE4}"]  

  jaeger:
      image: jaegertracing/all-in-one:latest
      container_name: 'hotel_app_jaeger'
      ports:
        - "14269"
        - "5778:5778"
        - "14268:14268"
        - "14267"
        - "16686:16686"
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
      deploy:
        restart_policy:
          condition: none          
        placement:
          constraints: ["node.hostname == ${NODE5}"]  
